### ISSUE TITLE
Observable object don't have catch method

### ISSUE THREAD

**Issue by samelabd** [gopinav/Angular-Tutorials#3]
Observable object don't have catch method
return this.http.get<IEmployee[]>(this._url).**catch**(this.errorHandler);

I'm using "rxjs": "^6.0.0"

**Comment by swethapm** [comment]
I am also getting the similiar issue as 

Property catch does not exist on type 'Observable<[IEmployee]>

**Comment by satya131428** [comment]
Hi Gopinav, I am also having same issue. Please suggest me to resolve the issue.

Property catch does not exist on type 'Observable<[IEmployee]>

**Comment by gopinav** [comment]
Please make sure to use the updated project for Rxjs 6 - https://github.com/gopinav/Angular-Tutorials/tree/master/v6-services-and-http

**Comment by gopinav** [comment]
Closing issue - Follow updated video above to resolve the issue
